name: ci-cd

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.run_number || github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  maven-install:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.CODEARTIFACT_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to AWS CodeArtifact
        run: |
          echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain fme --domain-owner 079419646996 --region us-east-1 --query authorizationToken --output text)" >> $GITHUB_ENV

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Setup Environment
        run: |
          cp ci.settings.xml ${HOME}/.m2/settings.xml

      - name: Maven package
        run: mvn --batch-mode -T 2C clean package
        env:
          MAVEN_OPTS: "-XX:InitialHeapSize=2G -XX:MaxHeapSize=2G -XX:+PrintCommandLineFlags -XX:ThreadStackSize=65536 -XX:-TieredCompilation"

      - name: Maven deploy
        if: ${{ github.event_name == 'push' }}
        run: mvn --batch-mode -T 2C deploy
